import { existsSync } from 'node:fs';
import path from 'node:path';
import { getCollection, getEntry } from 'astro:content';

export interface WeeklyIssue {
  number: number;
  slug: string;
  /** e.g. "AfterAI Weekly Vol.12" */
  title: string;
  /**
   * Site-relative path of the 1600px JPG, e.g. "/img/weekly/ja/vol12-ja.jpg".
   * Used for the "open full size" link and as the OG image (crawlers want JPG/PNG).
   */
  image: string;
  /** WebP derivatives generated by scripts/weekly-images.sh, keyed by pixel width. */
  webp: Record<400 | 800 | 1600, string>;
  /** Site-relative page URL, e.g. "/weekly/vol12/". */
  url: string;
  hasTranscription: boolean;
}

/** Resolved from the project root: at build time this module is bundled elsewhere, so import.meta.url is useless here. */
const PUBLIC_DIR = path.join(process.cwd(), 'public');

/**
 * Japanese artwork lives in /img/weekly/ja/; issues that were only drawn in
 * English fall back to /img/weekly/en/ (mirrors the old onerror fallback).
 * The WebP derivatives sit next to the JPG; the build fails loudly when one
 * is missing so a forgotten `scripts/weekly-images.sh volN` is caught here.
 */
function resolveImage(slug: string): Pick<WeeklyIssue, 'image' | 'webp'> {
  const ja = `/img/weekly/ja/${slug}-ja`;
  const base = existsSync(path.join(PUBLIC_DIR, `${ja}.jpg`)) ? ja : `/img/weekly/en/${slug}-en`;
  const webp = { 400: `${base}-400.webp`, 800: `${base}-800.webp`, 1600: `${base}-1600.webp` };
  for (const file of [`${base}.jpg`, ...Object.values(webp)]) {
    if (!existsSync(path.join(PUBLIC_DIR, file))) {
      throw new Error(`Weekly image missing: public${file} (run scripts/weekly-images.sh ${slug})`);
    }
  }
  return { image: `${base}.jpg`, webp };
}

/** `srcset` value for the given widths, e.g. "…-400.webp 400w, …-800.webp 800w". */
export function webpSrcset(issue: WeeklyIssue, widths: (400 | 800 | 1600)[]): string {
  return widths.map((w) => `${issue.webp[w]} ${w}w`).join(', ');
}

let cache: Promise<WeeklyIssue[]> | undefined;

/** All issues, newest first. */
export function getWeeklyIssues(): Promise<WeeklyIssue[]> {
  cache ??= (async () => {
    const [issues, transcriptions] = await Promise.all([
      getCollection('weekly'),
      getCollection('weeklyTranscriptions'),
    ]);
    const withTranscription = new Set(transcriptions.map((t) => t.id));
    return issues
      .map(({ data }) => ({
        number: data.number,
        slug: data.slug,
        title: `AfterAI Weekly Vol.${data.number}`,
        ...resolveImage(data.slug),
        url: `/weekly/${data.slug}/`,
        hasTranscription: withTranscription.has(data.slug),
      }))
      .sort((a, b) => b.number - a.number);
  })();
  return cache;
}

/** The newest issue. */
export async function getLatestIssue(): Promise<WeeklyIssue> {
  const [latest] = await getWeeklyIssues();
  if (!latest) throw new Error('No weekly issues found');
  return latest;
}

/** The transcription entry for an issue, or undefined when it has none. */
export function getTranscription(slug: string) {
  return getEntry('weeklyTranscriptions', slug);
}
